### ISSUE TITLE
Run scGNN without ground truth labels 

### ISSUE THREAD

**Issue by Ashduc** [OSU-BMBL/scGNN2.0#16]
Hello,
How to perform scGNN without ground truth labels?

When I run the command I get the below error.
python scGNN_v2.py --load_seurat_object counts.csv --output_dir .\seu_dir\ --total_epoch 31 --feature_AE_epoch 500 300 --output_intermediate
**TypeError: 'NoneType' object is not iterable**

This is a follow-up to my previous issue.

**Comment by Ashduc** [comment]
Thanks for the response. However, I get a different error now.
> Entering main loop ...
2023-08-16 21:56:49,767 - --------> Computing all metrics ...
Traceback (most recent call last):
  File "~\scGNN2.0-main\scGNN2.0-main\scGNN_v2.py", line 248, in <module>
    metrics = result.Performance_Metrics(X_sc, X_process, X_feature_recon, edgeList, ct_labels_truth, dropout_info, graph_embed, X_embed, args, param)
  File "~\scGNN2.0-main\scGNN2.0-main\result.py", line 78, in __init__
    self.update(self.cluster_labels_old, X_process, X_feature_recon, edgeList, graph_embed, X_embed, param)
  File "~\scGNN2.0-main\scGNN2.0-main\result.py", line 94, in update
    ari_against_ground_truth = None if self.given_cell_type_labels else self.unused_metric_names.append['ari_against_ground_truth']        
**TypeError: 'builtin_function_or_method' object is not subscriptable**

**Comment by chthub** [comment]
Hi @Ashduc,

This is a grammar error. Please modify `File "~\scGNN2.0-main\scGNN2.0-main\result.py", line 94, in update` to:
```python
ari_against_ground_truth = None if self.given_cell_type_labels else self.unused_metric_names.append('ari_against_ground_truth')
```

**Comment by victorwang123** [comment]
Hi, when I follow the steps above, I got a new problem, how to deal with it ? thx
`Traceback (most recent call last):
  File "scGNN_v2.py", line 273, in <module>
    metrics.update(cluster_labels, X_imputed_sc, X_feature_recon, edgeList, graph_embed, X_embed, param)
  File "scGNN/scGNN2.0/result.py", line 190, in update
    self.output_intermediate_results(cluster_labels, graph_embed, X_embed, param) if self.output_intermediate else None
  File "scGNN/scGNN2.0/result.py", line 246, in output_intermediate_results
    util.drawUMAP(param['clustering_embed'], cluster_labels, output_dir, filename_suffix=f'pred_{epoch_num}')
  File "scGNN/scGNN2.0/util.py", line 109, in drawUMAP
    embedding = reducer.fit_transform(z)
  File "/miniconda3/envs/scgnnEnv/lib/python3.8/site-packages/umap/umap_.py", line 1598, in fit_transform
    self.fit(X, y)
  File "/miniconda3/envs/scgnnEnv/lib/python3.8/site-packages/umap/umap_.py", line 1452, in fit
    self._search_graph.transpose()
  File "/miniconda3/envs/scgnnEnv/lib/python3.8/site-packages/scipy/sparse/_lil.py", line 436, in transpose
    return self.tocsr(copy=copy).transpose(axes=axes, copy=False).tolil(copy=False)
  File "/miniconda3/envs/scgnnEnv/lib/python3.8/site-packages/scipy/sparse/_lil.py", line 459, in tocsr
    _csparsetools.lil_get_lengths(self.rows, indptr[1:])
  File "_csparsetools.pyx", line 109, in scipy.sparse._csparsetools.lil_get_lengths
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)`

**Comment by chthub** [comment]
Hi @victorwang123,

It seems that the error occurs when ploting UMAP using the embeddings. Could you please check the shape and value of `param['clustering_embed']`?

**Comment by feanaros** [comment]
hi, I got the same error as @victorwang123 .
did you solve it?

**Comment by chthub** [comment]
> hi, I got the same error as @victorwang123 . did you solve it?

The error traceback you're encountering (ValueError: Buffer has wrong number of dimensions (expected 1, got 2)) suggests there's an issue with the dimensions of a buffer being passed somewhere in your code.

Check Input Dimensions: Ensure that the input data structures (like sparse matrices or arrays) being passed to functions expecting 1-dimensional buffers are correctly formatted. This often involves inspecting how your data is prepared or processed before it reaches the problematic function (drawUMAP in util.py).

Inspect Function Calls: Review the function drawUMAP in your util.py file where the error originates (scGNN/scGNN2.0/util.py, line 109). Verify the inputs (param['clustering_embed'], cluster_labels, etc.) to drawUMAP and ensure they match the expected format and dimensions for UMAP operations.

Debugging in Context: If possible, print or log the shapes and types of the variables (z, param['clustering_embed'], cluster_labels, etc.) just before the call to fit_transform in UMAP (umap_.py). This can help you understand if there's a mismatch in dimensions or unexpected types being passed.

**Comment by feanaros** [comment]
Hi @chthub, I followed the tutorial importing the Matrix from Seurat in csv. Unfortunately, I'm not very confident with python and I am not able to follow you. I have to modify something in utils.py?
